Cleaning a student score data : -create a year column -re-arrange column values -create a data with student id with unique teacher id for each subject.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings('ignore')

In [ ]:
df_20_21 = pd.read_csv('/content/drive/MyDrive/Data project folder/Colonial Student File 21.csv')
df_20_21.head()

,Year,Student ID,Grade,Building,School,Race/Ethnicity,Race,FRL Status,ELL Status,SPED Status,General Education Teacher ID,Gen Ed Teacher Effect,ELA Teacher ID,Math Teacher ID,ELA Standardized Test,Math Standardized Test,ELA Score,ELA Proficiency Level,Math Score,Math Proficiency Level
0,2021,880126,3,456,Eisenberg Elementary,4,Black or African American,NaN,N,N,13244,0.9,13244,13244,SBAC,SBAC,NaN,NaN,NaN,NaN
1,2021,134069,3,456,Eisenberg Elementary,4,Black or African American,NaN,N,N,13244,0.9,13244,13244,SBAC,SBAC,NaN,NaN,NaN,NaN
2,2021,180661,3,456,Eisenberg Elementary,4,Black or African American,NaN,N,N,13244,0.9,13244,13244,SBAC,SBAC,2344.0,1.0,2291.0,1.0
3,2021,223542,3,456,Eisenberg Elementary,1,Hispanic or Latino of any race,NaN,Y,N,13244,0.9,13244,13244,SBAC,SBAC,NaN,NaN,NaN,NaN
4,2021,136545,3,456,Eisenberg Elementary,4,Black or African American,NaN,N,N,13244,0.9,13244,13244,SBAC,SBAC,NaN,NaN,NaN,NaN

In [ ]:
df_20_21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5484 entries, 0 to 5483
Data columns (total 20 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Year                          5484 non-null   int64
 1   Student ID                    5484 non-null   int64
 2   Grade                         5484 non-null   int64
 3   Building                      5484 non-null   int64
 4   School                        5484 non-null   object
 5   Race/Ethnicity                5484 non-null   int64
 6   Race                          5484 non-null   object
 7   FRL Status                    0 non-null      float64
 8   ELL Status                    5484 non-null   object
 9   SPED Status                   5484 non-null   object
 10  General Education Teacher ID  1750 non-null   object
 11  Gen Ed Teacher Effect         3288 non-null   float64
 12  ELA Teacher ID                3643 non-null   object
 13  Math Teacher ID               3355 non-null   object
 14  ELA Standardized Test         5484 non-null   object
 15  Math Standardized Test        5484 non-null   object
 16  ELA Score                     2322 non-null   float64
 17  ELA Proficiency Level         2322 non-null   float64
 18  Math Score                    2301 non-null   float64
 19  Math Proficiency Level        2301 non-null   float64
dtypes: float64(6), int64(5), object(9)
memory usage: 857.0+ KB

In [ ]:
df_20_21['Academic Year'] = '2020-2021'
df_20_21['District'] = 'COLONIAL'

df_20_21=df_20_21[['Student ID', 'Academic Year',
                   'District', 'School',
                   'Grade', 'Race',
                   'ELA Teacher ID', 'ELA Score', 'ELA Proficiency Level',
                   'Math Teacher ID', 'Math Score','Math Proficiency Level']]
df_20_21=df_20_21.rename(columns={'Race':'Race/Ethnicity'})

In [ ]:
df_20_21.loc[df_20_21['Student ID'].duplicated()]

Empty DataFrame
Columns: [Student ID, Academic Year, District, School, Grade, Race/Ethnicity, ELA Teacher ID, ELA Score, ELA Proficiency Level, Math Teacher ID, Math Score, Math Proficiency Level]
Index: []

In [ ]:
#select the columns with ela score and proficiency.
df_20_21_ela=df_20_21[[
    'Student ID','Academic Year','District', 'Grade','Race/Ethnicity',
    'ELA Teacher ID','ELA Score','ELA Proficiency Level','School']]
#add column
df_20_21_ela['Course']='ELA'
#drop null values
df_20_21_ela = df_20_21_ela.dropna(
    how='any',
    subset=['ELA Teacher ID', 'ELA Score', 'ELA Proficiency Level'])
df_20_21_ela=df_20_21_ela.rename(
    columns={'ELA Teacher ID':'Teacher ID',
             'ELA Score':'Score', 'ELA Proficiency Level':'Proficiency Level'})
#change the type of score from float to integer
df_20_21_ela['Score'] = df_20_21_ela['Score'].astype('int')

In [ ]:
df_20_21_math=df_20_21[[
    'Student ID','Academic Year','District', 'Grade','Race/Ethnicity',
    'Math Teacher ID','Math Score','Math Proficiency Level','School']]
df_20_21_math['Course']='MATH'
df_20_21_math = df_20_21_math.dropna(
    how='any',
    subset=['Math Teacher ID', 'Math Score', 'Math Proficiency Level'])
df_20_21_math=df_20_21_math.rename(
    columns={'Math Teacher ID':'Teacher ID',
             'Math Score':'Score',
             'Math Proficiency Level':'Proficiency Level'})

df_20_21_math['Score'] = df_20_21_math['Score'].astype('int')

In [ ]:
#append both ela and maths score
df_20_21 = pd.concat([df_20_21_ela, df_20_21_math], axis=0)

In [ ]:

df_c1 = (df_20_21.groupby('Student ID')['District'].count().reset_index())
assert len(df_c1[df_c1['District']>2]) == 0

In [ ]:
df_20_21.to_csv('/content/drive/MyDrive/Data project folder/Colonial Student File 21_clean.csv',
                index=False, encoding='utf-8')